#ifndef GUARD_CONSTANTS_ABILITY_SWAPPER_H
#define GUARD_CONSTANTS_ABILITY_SWAPPER_H

enum AbilitySwapperResult
{
    ABILITY_SWAPPER_RESULT_READY,
    ABILITY_SWAPPER_RESULT_SWAPPED,
    ABILITY_SWAPPER_RESULT_CANCELLED,
    ABILITY_SWAPPER_RESULT_NO_HEART_SCALE,
    ABILITY_SWAPPER_RESULT_EGG,
    ABILITY_SWAPPER_RESULT_HIDDEN_ABILITY,
    ABILITY_SWAPPER_RESULT_NO_ORDINARY_SWAP,
};

#endif // GUARD_CONSTANTS_ABILITY_SWAPPER_H
