#ifndef GUARD_CONSTANTS_CONDITION_COACH_H
#define GUARD_CONSTANTS_CONDITION_COACH_H

enum ConditionCoachChoice
{
    CONDITION_COACH_CHOICE_BURN,
    CONDITION_COACH_CHOICE_POISON,
    CONDITION_COACH_CHOICE_PARALYSIS,
    CONDITION_COACH_CHOICE_REST_WAKE,
    CONDITION_COACH_CHOICE_CLEAR,
    CONDITION_COACH_CHOICE_EXIT,
};

enum ConditionCoachResult
{
    CONDITION_COACH_RESULT_APPLIED,
    CONDITION_COACH_RESULT_CANCELLED,
    CONDITION_COACH_RESULT_EGG,
    CONDITION_COACH_RESULT_FAINTED,
    CONDITION_COACH_RESULT_ALREADY_STATUS,
    CONDITION_COACH_RESULT_ALREADY_CLEAR,
    CONDITION_COACH_RESULT_INVALID_CHOICE,
    CONDITION_COACH_RESULT_LOCKED,
};

enum ConditionCoachHint
{
    CONDITION_COACH_HINT_NONE,
    CONDITION_COACH_HINT_CURING_ITEM,
    CONDITION_COACH_HINT_GUTS,
    CONDITION_COACH_HINT_MARVEL_SCALE,
    CONDITION_COACH_HINT_QUICK_FEET,
    CONDITION_COACH_HINT_POISON_HEAL,
    CONDITION_COACH_HINT_TOXIC_BOOST,
    CONDITION_COACH_HINT_FLARE_BOOST,
    CONDITION_COACH_HINT_MAGIC_GUARD,
    CONDITION_COACH_HINT_STATUS_MAY_SLIP,
    CONDITION_COACH_HINT_REST_WAKE,
    CONDITION_COACH_HINT_CLEAR,
};

#endif // GUARD_CONSTANTS_CONDITION_COACH_H
