#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10
#define HIDDEN_WILD_COUNT   3

#define WILD_ENCOUNTER_RESULT_NONE             0
#define WILD_ENCOUNTER_RESULT_STARTED          1
#define WILD_ENCOUNTER_RESULT_HIGHLANDER_EMPTY 2
#define WILD_ENCOUNTER_RESULT_BOUNDARY_CLAIMED 3

#define NUM_ALTERING_CAVE_TABLES 9

#define FISHING_CHAIN_LENGTH_MAX 200
#define FISHING_CHAIN_SHINY_STREAK_MAX 20

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
