#include "global.h"
#include "test/battle.h"
#include "battle_ai_field_statuses.h"
#include "battle_ai_util.h"

AI_SINGLE_BATTLE_TEST("Shared Power AI: avoids Thunder Wave when pooled Limber")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_LIMBER); }
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE, MOVE_THUNDER_WAVE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
        TURN { MOVE(player, MOVE_SPLASH); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: avoids Will-O-Wisp when pooled Water Veil")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_WATER_VEIL); }
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE, MOVE_WILL_O_WISP); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
        TURN { MOVE(player, MOVE_SPLASH); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: avoids Thunderbolt when pooled Lightning Rod")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_MANECTRIC) { Ability(ABILITY_LIGHTNING_ROD); }
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_THUNDERBOLT, MOVE_SCRATCH); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_SCRATCH); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: avoids Hyper Voice when pooled Soundproof")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(IsSoundMove(MOVE_HYPER_VOICE));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_ELECTRODE) { Ability(ABILITY_SOUNDPROOF); }
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_HYPER_VOICE, MOVE_SCRATCH); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_SCRATCH); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Soundproof blocks Roar prediction")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_ROAR) == EFFECT_ROAR);
        ASSUME(IsSoundMove(MOVE_ROAR));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_VOLTORB) { Ability(ABILITY_SOUNDPROOF); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(AI_HasActiveAbility(B_POSITION_PLAYER_LEFT, ABILITY_SOUNDPROOF));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Soundproof does not block Roar prediction")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_ROAR) == EFFECT_ROAR);
        ASSUME(IsSoundMove(MOVE_ROAR));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_VOLTORB) { Ability(ABILITY_SOUNDPROOF); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(!AI_HasActiveAbility(B_POSITION_PLAYER_LEFT, ABILITY_SOUNDPROOF));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Suction Cups lowers Roar score")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_ROAR) == EFFECT_ROAR);
        ASSUME(GetMoveEffect(MOVE_SWORDS_DANCE) == EFFECT_ATTACK_UP_2);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_OCTILLERY) { Ability(ABILITY_SUCTION_CUPS); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SWORDS_DANCE, MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_ROAR, MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); }
        TURN { MOVE(player, MOVE_SWORDS_DANCE); SCORE_LT_VAL(opponent, MOVE_ROAR, AI_SCORE_DEFAULT); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Suction Cups does not lower Roar score")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_ROAR) == EFFECT_ROAR);
        ASSUME(GetMoveEffect(MOVE_SWORDS_DANCE) == EFFECT_ATTACK_UP_2);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_OCTILLERY) { Ability(ABILITY_SUCTION_CUPS); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SWORDS_DANCE, MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_ROAR, MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); }
        TURN { MOVE(player, MOVE_SWORDS_DANCE); SCORE_EQ_VAL(opponent, MOVE_ROAR, 90); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: scores Perish Song as bad against pooled Soundproof")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_PERISH_SONG) == EFFECT_PERISH_SONG);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_VOLTORB) { Ability(ABILITY_SOUNDPROOF); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE, MOVE_PERISH_SONG); }
        OPPONENT(SPECIES_WYNAUT);
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_PERISH_SONG); }
        TURN { MOVE(player, MOVE_SPLASH); SCORE_LT_VAL(opponent, MOVE_PERISH_SONG, AI_SCORE_DEFAULT); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Soundproof does not make Perish Song score bad")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_PERISH_SONG) == EFFECT_PERISH_SONG);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_VOLTORB) { Ability(ABILITY_SOUNDPROOF); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE, MOVE_PERISH_SONG); }
        OPPONENT(SPECIES_WYNAUT);
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_PERISH_SONG); }
        TURN { MOVE(player, MOVE_SPLASH); SCORE_GT_VAL(opponent, MOVE_PERISH_SONG, 90); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Overcoat blocks powder prediction")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(IsPowderMove(MOVE_SPORE));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_PINECO) { Ability(ABILITY_OVERCOAT); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(!AI_IsAffectedByPowder(B_POSITION_PLAYER_LEFT));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Overcoat does not block powder prediction")
{
    GIVEN {
        ASSUME(IsPowderMove(MOVE_SPORE));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_PINECO) { Ability(ABILITY_OVERCOAT); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(AI_IsAffectedByPowder(B_POSITION_PLAYER_LEFT));
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: avoids Stealth Rock when pooled Magic Bounce")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_STEALTH_ROCK) == EFFECT_STEALTH_ROCK);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_POWERFUL_STATUS | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SPLASH, MOVE_CELEBRATE); }
        PLAYER(SPECIES_ESPEON) { Ability(ABILITY_MAGIC_BOUNCE); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT);
        OPPONENT(SPECIES_GLIGAR) { Moves(MOVE_STEALTH_ROCK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SCORE_LT(opponentLeft, MOVE_STEALTH_ROCK, MOVE_CELEBRATE, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: AI may set Stealth Rock into partner Magic Bounce")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_STEALTH_ROCK) == EFFECT_STEALTH_ROCK);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_POWERFUL_STATUS | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SPLASH, MOVE_CELEBRATE); }
        PLAYER(SPECIES_ESPEON) { Ability(ABILITY_MAGIC_BOUNCE); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT);
        OPPONENT(SPECIES_GLIGAR) { Moves(MOVE_STEALTH_ROCK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SCORE_EQ(opponentLeft, MOVE_STEALTH_ROCK, MOVE_CELEBRATE, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: avoids Heal Bell when pooled Soundproof blocks the active partner cure")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_HEAL_BELL) == EFFECT_HEAL_BELL);
        ASSUME(IsSoundMove(MOVE_HEAL_BELL));
        WITH_CONFIG(GEN_CONFIG_HEAL_BELL_SOUNDPROOF, GEN_8);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_EXPLOUD) { Ability(ABILITY_SOUNDPROOF); Moves(MOVE_ROCK_SLIDE, MOVE_HEAL_BELL, MOVE_ACID); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Status1(STATUS1_PARALYSIS); }
    } WHEN {
        TURN { EXPECT_MOVE(opponentLeft, MOVE_ROCK_SLIDE); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: AI may use Heal Bell for a non-Soundproof active partner")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_HEAL_BELL) == EFFECT_HEAL_BELL);
        ASSUME(IsSoundMove(MOVE_HEAL_BELL));
        WITH_CONFIG(GEN_CONFIG_HEAL_BELL_SOUNDPROOF, GEN_8);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_EXPLOUD) { Ability(ABILITY_SOUNDPROOF); Moves(MOVE_ROCK_SLIDE, MOVE_HEAL_BELL, MOVE_ACID); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Status1(STATUS1_PARALYSIS); }
    } WHEN {
        TURN { EXPECT_MOVE(opponentLeft, MOVE_HEAL_BELL); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: switches out against pooled Wonder Guard")
{
    PASSES_RANDOMLY(SHOULD_SWITCH_WONDER_GUARD_PERCENTAGE, 100, RNG_AI_SWITCH_WONDER_GUARD);
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveType(MOVE_BRICK_BREAK) == TYPE_FIGHTING);
        ASSUME(GetMoveType(MOVE_SCRATCH) == TYPE_NORMAL);
        ASSUME(GetMoveType(MOVE_SHADOW_BALL) == TYPE_GHOST);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_SMART_SWITCHING | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_ZIGZAGOON) { Ability(ABILITY_WONDER_GUARD); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_BRICK_BREAK, MOVE_SCRATCH); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_SHADOW_BALL); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_BRICK_BREAK); }
        TURN { MOVE(player, MOVE_SPLASH); EXPECT_SWITCH(opponent, 1); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: AI does not switch out for partner Wonder Guard")
{
    GIVEN {
        ASSUME(GetMoveType(MOVE_BRICK_BREAK) == TYPE_FIGHTING);
        ASSUME(GetMoveType(MOVE_SCRATCH) == TYPE_NORMAL);
        ASSUME(GetMoveType(MOVE_SHADOW_BALL) == TYPE_GHOST);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_SMART_SWITCHING | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_ZIGZAGOON) { Ability(ABILITY_WONDER_GUARD); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_BRICK_BREAK, MOVE_SCRATCH); }
        OPPONENT(SPECIES_ZIGZAGOON) { Moves(MOVE_SHADOW_BALL); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_BRICK_BREAK); }
        TURN { MOVE(player, MOVE_SPLASH); EXPECT_MOVE(opponent, MOVE_SCRATCH); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: scores fixed damage lower into pooled Wonder Guard")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_DRAGON_RAGE) == EFFECT_FIXED_HP_DAMAGE);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_ZIGZAGOON) { Ability(ABILITY_WONDER_GUARD); Moves(MOVE_SPLASH, MOVE_NONE, MOVE_NONE, MOVE_NONE); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH, MOVE_NONE, MOVE_NONE, MOVE_NONE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_DRAGON_RAGE, MOVE_CELEBRATE, MOVE_NONE, MOVE_NONE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
        TURN { MOVE(player, MOVE_SPLASH); SCORE_LT_VAL(opponent, MOVE_DRAGON_RAGE, AI_SCORE_DEFAULT); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Wonder Guard does not lower fixed damage score")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_DRAGON_RAGE) == EFFECT_FIXED_HP_DAMAGE);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_ZIGZAGOON) { Ability(ABILITY_WONDER_GUARD); Moves(MOVE_SPLASH, MOVE_NONE, MOVE_NONE, MOVE_NONE); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH, MOVE_NONE, MOVE_NONE, MOVE_NONE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_DRAGON_RAGE, MOVE_CELEBRATE, MOVE_NONE, MOVE_NONE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_DRAGON_RAGE); }
        TURN { MOVE(player, MOVE_SPLASH); SCORE_EQ_VAL(opponent, MOVE_DRAGON_RAGE, AI_SCORE_DEFAULT); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Magic Guard prevents secondary damage prediction")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_CLEFAIRY) { Ability(ABILITY_MAGIC_GUARD); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Status1(STATUS1_POISON); HP(100); MaxHP(100); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT_EQ(GetBattlerSecondaryDamage(B_POSITION_PLAYER_LEFT), 0);
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Magic Guard does not prevent secondary damage prediction")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_CLEFAIRY) { Ability(ABILITY_MAGIC_GUARD); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Status1(STATUS1_POISON); HP(100); MaxHP(100); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT_GT(GetBattlerSecondaryDamage(B_POSITION_PLAYER_LEFT), 0);
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Poison Heal prevents poison damage prediction")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_SHROOMISH) { Ability(ABILITY_POISON_HEAL); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Status1(STATUS1_POISON); HP(100); MaxHP(100); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT_EQ(GetBattlerSecondaryDamage(B_POSITION_PLAYER_LEFT), 0);
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Poison Heal does not prevent poison damage prediction")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_SHROOMISH) { Ability(ABILITY_POISON_HEAL); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Status1(STATUS1_POISON); HP(100); MaxHP(100); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT_GT(GetBattlerSecondaryDamage(B_POSITION_PLAYER_LEFT), 0);
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Comatose treats active battlers as asleep")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_KOMALA) { Ability(ABILITY_COMATOSE); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(AI_IsBattlerAsleepOrComatose(B_POSITION_PLAYER_LEFT));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Comatose does not make active battlers asleep")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_KOMALA) { Ability(ABILITY_COMATOSE); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(!AI_IsBattlerAsleepOrComatose(B_POSITION_PLAYER_LEFT));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Inner Focus prevents guaranteed flinch prediction")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(MoveHasAdditionalEffectWithChance(MOVE_FAKE_OUT, MOVE_EFFECT_FLINCH, 100));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_INNER_FOCUS); Speed(1); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Speed(1); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(100); Moves(MOVE_FAKE_OUT); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_FAKE_OUT); }
    } THEN {
        EXPECT(!IsFlinchGuaranteed(B_POSITION_OPPONENT_LEFT, B_POSITION_PLAYER_LEFT, MOVE_FAKE_OUT));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Inner Focus does not prevent guaranteed flinch prediction")
{
    GIVEN {
        ASSUME(MoveHasAdditionalEffectWithChance(MOVE_FAKE_OUT, MOVE_EFFECT_FLINCH, 100));
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_INNER_FOCUS); Speed(1); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Speed(1); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(100); Moves(MOVE_FAKE_OUT); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_FAKE_OUT); }
    } THEN {
        EXPECT(IsFlinchGuaranteed(B_POSITION_OPPONENT_LEFT, B_POSITION_PLAYER_LEFT, MOVE_FAKE_OUT));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Swift Swim makes rain beneficial")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_SWIFT_SWIM); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(WeatherChecker(B_POSITION_PLAYER_LEFT, B_WEATHER_RAIN, FIELD_EFFECT_POSITIVE));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Swift Swim does not make rain beneficial")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_SWIFT_SWIM); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(!WeatherChecker(B_POSITION_PLAYER_LEFT, B_WEATHER_RAIN, FIELD_EFFECT_POSITIVE));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Surge Surfer makes Electric Terrain beneficial")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_SURGE_SURFER); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(FieldStatusChecker(B_POSITION_PLAYER_LEFT, STATUS_FIELD_ELECTRIC_TERRAIN, FIELD_EFFECT_POSITIVE));
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Surge Surfer does not make Electric Terrain beneficial")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_SURGE_SURFER); Moves(MOVE_SPLASH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SPLASH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SWITCH(player, 1); EXPECT_MOVE(opponent, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(!FieldStatusChecker(B_POSITION_PLAYER_LEFT, STATUS_FIELD_ELECTRIC_TERRAIN, FIELD_EFFECT_POSITIVE));
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores healing an ally through pooled Volt Absorb")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_HP_AWARE);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_JOLTEON) { Ability(ABILITY_VOLT_ABSORB); Moves(MOVE_THUNDERBOLT, MOVE_SCRATCH); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); HP(1); MaxHP(100); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SCORE_GT_VAL(opponentLeft, MOVE_THUNDERBOLT, 90, target: opponentRight); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Volt Absorb does not score ally healing")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_HP_AWARE);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_JOLTEON) { Ability(ABILITY_VOLT_ABSORB); Moves(MOVE_THUNDERBOLT, MOVE_SCRATCH); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); HP(1); MaxHP(100); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_THUNDERBOLT, 90, target: opponentRight); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores Electrify higher with pooled Volt Absorb")
{
    PASSES_RANDOMLY(PREDICT_MOVE_CHANCE, 100, RNG_AI_PREDICT_MOVE);
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_ELECTRIFY) == EFFECT_ELECTRIFY);
        AI_FLAGS(AI_FLAG_CHECK_VIABILITY | AI_FLAG_OMNISCIENT | AI_FLAG_PREDICT_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SCRATCH, MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_GLIGAR) { Ability(ABILITY_TELEPATHY); Moves(MOVE_ELECTRIFY, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_JOLTEON) { Ability(ABILITY_VOLT_ABSORB); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { MOVE(playerLeft, MOVE_SCRATCH, target: opponentLeft); SCORE_GT(opponentLeft, MOVE_ELECTRIFY, MOVE_CELEBRATE, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Volt Absorb does not raise Electrify score")
{
    PASSES_RANDOMLY(PREDICT_MOVE_CHANCE, 100, RNG_AI_PREDICT_MOVE);
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_ELECTRIFY) == EFFECT_ELECTRIFY);
        AI_FLAGS(AI_FLAG_CHECK_VIABILITY | AI_FLAG_OMNISCIENT | AI_FLAG_PREDICT_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_SCRATCH, MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_GLIGAR) { Ability(ABILITY_TELEPATHY); Moves(MOVE_ELECTRIFY, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_JOLTEON) { Ability(ABILITY_VOLT_ABSORB); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { MOVE(playerLeft, MOVE_SCRATCH, target: opponentLeft); SCORE_EQ(opponentLeft, MOVE_ELECTRIFY, MOVE_CELEBRATE, target: playerLeft); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power AI: pooled Defiant prevents stat-drop score boosts")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_GROWL) == EFFECT_ATTACK_DOWN);
        AI_FLAGS(AI_FLAG_CHECK_VIABILITY | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_MANKEY) { Ability(ABILITY_DEFIANT); Moves(MOVE_SCRATCH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SCRATCH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_GROWL, MOVE_CELEBRATE, MOVE_NONE, MOVE_NONE); }
    } WHEN {
        TURN { SWITCH(player, 1); }
        TURN { MOVE(player, MOVE_SCRATCH); SCORE_EQ_VAL(opponent, MOVE_GROWL, AI_SCORE_DEFAULT); }
    }
}

AI_SINGLE_BATTLE_TEST("Shared Power off: partner Defiant does not block stat-drop score boosts")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_GROWL) == EFFECT_ATTACK_DOWN);
        AI_FLAGS(AI_FLAG_CHECK_VIABILITY | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_MANKEY) { Ability(ABILITY_DEFIANT); Moves(MOVE_SCRATCH); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SCRATCH); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_GROWL, MOVE_CELEBRATE, MOVE_NONE, MOVE_NONE); }
    } WHEN {
        TURN { SWITCH(player, 1); }
        TURN { MOVE(player, MOVE_SCRATCH); SCORE_GT_VAL(opponent, MOVE_GROWL, AI_SCORE_DEFAULT); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: pooled Sticky Hold prevents item-loss prediction")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_MUK) { Ability(ABILITY_STICKY_HOLD); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Item(ITEM_LIFE_ORB); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponentLeft, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(!CanKnockOffItem(B_POSITION_OPPONENT_RIGHT, ITEM_LIFE_ORB));
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Sticky Hold does not prevent item-loss prediction")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_MUK) { Ability(ABILITY_STICKY_HOLD); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Item(ITEM_LIFE_ORB); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponentLeft, MOVE_CELEBRATE); }
    } THEN {
        EXPECT(CanKnockOffItem(B_POSITION_OPPONENT_RIGHT, ITEM_LIFE_ORB));
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores direct drain moves as bad into pooled Liquid Ooze")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_ABSORB) == EFFECT_ABSORB);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_TENTACOOL) { Ability(ABILITY_LIQUID_OOZE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_ABSORB, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_LT_VAL(opponentLeft, MOVE_ABSORB, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Liquid Ooze does not affect direct drain prediction")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_ABSORB) == EFFECT_ABSORB);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_TENTACOOL) { Ability(ABILITY_LIQUID_OOZE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_ABSORB, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_ABSORB, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores Substitute lower against pooled Infiltrator")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_SUBSTITUTE) == EFFECT_SUBSTITUTE);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_ZUBAT) { Ability(ABILITY_INFILTRATOR); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(100); MaxHP(100); Moves(MOVE_SUBSTITUTE, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_LT_VAL(opponentLeft, MOVE_SUBSTITUTE, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Infiltrator does not lower Substitute score")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_SUBSTITUTE) == EFFECT_SUBSTITUTE);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_ZUBAT) { Ability(ABILITY_INFILTRATOR); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(100); MaxHP(100); Moves(MOVE_SUBSTITUTE, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_SUBSTITUTE, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores Magnitude lower against pooled Levitate")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_MAGNITUDE) == EFFECT_MAGNITUDE);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_UNOWN) { Ability(ABILITY_LEVITATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_MAGNITUDE, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_LT_VAL(opponentLeft, MOVE_MAGNITUDE, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Levitate does not lower Magnitude score")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_MAGNITUDE) == EFFECT_MAGNITUDE);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_UNOWN) { Ability(ABILITY_LEVITATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_MAGNITUDE, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_MAGNITUDE, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores Lock-On lower when pooled No Guard already guarantees accuracy")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_LOCK_ON) == EFFECT_LOCK_ON);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_MACHAMP) { Ability(ABILITY_NO_GUARD); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_LOCK_ON, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_LT_VAL(opponentLeft, MOVE_LOCK_ON, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner No Guard does not lower Lock-On score")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_LOCK_ON) == EFFECT_LOCK_ON);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_MACHAMP) { Ability(ABILITY_NO_GUARD); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_LOCK_ON, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_LOCK_ON, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores Laser Focus lower against pooled Battle Armor")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_LASER_FOCUS) == EFFECT_LASER_FOCUS);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_KABUTO) { Ability(ABILITY_BATTLE_ARMOR); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_LASER_FOCUS, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_LT_VAL(opponentLeft, MOVE_LASER_FOCUS, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Battle Armor does not lower Laser Focus score")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_LASER_FOCUS) == EFFECT_LASER_FOCUS);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_KABUTO) { Ability(ABILITY_BATTLE_ARMOR); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_LASER_FOCUS, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_LASER_FOCUS, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: does not score giving Black Sludge to pooled Magic Guard targets")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(GetMoveEffect(MOVE_TRICK) == EFFECT_TRICK);
        ASSUME(gItemsInfo[ITEM_BLACK_SLUDGE].holdEffect == HOLD_EFFECT_BLACK_SLUDGE);
        AI_FLAGS(AI_FLAG_CHECK_VIABILITY);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_CLEFAIRY) { Ability(ABILITY_MAGIC_GUARD); }
        OPPONENT(SPECIES_WOBBUFFET) { Item(ITEM_BLACK_SLUDGE); Moves(MOVE_TRICK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_TRICK, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Magic Guard does not stop Black Sludge Trick scoring")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_TRICK) == EFFECT_TRICK);
        ASSUME(gItemsInfo[ITEM_BLACK_SLUDGE].holdEffect == HOLD_EFFECT_BLACK_SLUDGE);
        AI_FLAGS(AI_FLAG_CHECK_VIABILITY);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        PLAYER(SPECIES_CLEFAIRY) { Ability(ABILITY_MAGIC_GUARD); }
        OPPONENT(SPECIES_WOBBUFFET) { Item(ITEM_BLACK_SLUDGE); Moves(MOVE_TRICK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { SCORE_GT_VAL(opponentLeft, MOVE_TRICK, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power AI: scores Prankster status moves lower into Dark targets")
{
    GIVEN {
        BATTLE_TYPE(BATTLE_TYPE_SHARED_POWER);
        ASSUME(B_PRANKSTER_DARK_TYPES >= GEN_7);
        ASSUME(GetSpeciesType(SPECIES_POOCHYENA, 0) == TYPE_DARK);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_POOCHYENA) { Ability(ABILITY_RUN_AWAY); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SAND_ATTACK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_VOLBEAT) { Ability(ABILITY_PRANKSTER); }
    } WHEN {
        TURN { SCORE_LT_VAL(opponentLeft, MOVE_SAND_ATTACK, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}

AI_DOUBLE_BATTLE_TEST("Shared Power off: partner Prankster does not lower status moves into Dark targets")
{
    GIVEN {
        ASSUME(B_PRANKSTER_DARK_TYPES >= GEN_7);
        ASSUME(GetSpeciesType(SPECIES_POOCHYENA, 0) == TYPE_DARK);
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE);
        PLAYER(SPECIES_POOCHYENA) { Ability(ABILITY_RUN_AWAY); }
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_SAND_ATTACK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_VOLBEAT) { Ability(ABILITY_PRANKSTER); }
    } WHEN {
        TURN { SCORE_EQ_VAL(opponentLeft, MOVE_SAND_ATTACK, AI_SCORE_DEFAULT, target: playerLeft); }
    }
}
