#ifndef GUARD_JOURNEY_NPC_SPRITE_PREVIEW_H
#define GUARD_JOURNEY_NPC_SPRITE_PREVIEW_H

#if AUTOMATION_PROBE
enum JourneyNpcSpritePreviewMode
{
    JOURNEY_NPC_SPRITE_PREVIEW_ALL,
    JOURNEY_NPC_SPRITE_PREVIEW_BARRY_TRAINER,
    JOURNEY_NPC_SPRITE_PREVIEW_BARRY_OW_SOUTH,
    JOURNEY_NPC_SPRITE_PREVIEW_BARRY_OW_NORTH,
    JOURNEY_NPC_SPRITE_PREVIEW_BARRY_OW_WEST,
    JOURNEY_NPC_SPRITE_PREVIEW_BARRY_OW_EAST,
};

void CB2_InitJourneyNpcSpritePreview(u32 mode);
#endif

#endif // GUARD_JOURNEY_NPC_SPRITE_PREVIEW_H
